param(
    [string[]]$RootPath,
    [string]$OutputPath,
    [ValidateSet('table', 'json', 'markdown')]
    [string]$Format
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem

function Get-DefaultStencilRoots {
    $roots = @()
    if ($env:ProgramFiles) {
        $roots += Join-Path $env:ProgramFiles 'Microsoft Office\root\Office16\Visio Content'
    }
    if (${env:ProgramFiles(x86)}) {
        $roots += Join-Path ${env:ProgramFiles(x86)} 'Microsoft Office\root\Office16\Visio Content'
    }
    if ($env:USERPROFILE) {
        $roots += Join-Path $env:USERPROFILE 'Documents\My Shapes'
    }
    return @($roots | Select-Object -Unique)
}

function Read-VssxMasters([string]$path) {
    $masters = @()
    $seen = @{}
    $archive = $null
    try {
        $archive = [IO.Compression.ZipFile]::OpenRead($path)
        $entry = $archive.Entries |
            Where-Object { $_.FullName -ieq 'visio/masters/masters.xml' } |
            Select-Object -First 1
        if ($null -eq $entry) { return @($masters) }

        $reader = New-Object IO.StreamReader($entry.Open())
        try {
            [xml]$xml = $reader.ReadToEnd()
        } finally {
            $reader.Dispose()
        }

        foreach ($master in @($xml.SelectNodes("//*[local-name()='Master']"))) {
            $displayName = [string]$master.Name
            $nameU = [string]$master.NameU
            $key = [string]$(if ($displayName) { $displayName } else { $nameU })
            if ($key -and -not $seen.ContainsKey($key)) {
                $seen[$key] = $true
                $masters += [pscustomobject]@{
                    Name = $displayName
                    NameU = $nameU
                    ID = [string]$master.ID
                }
            }
        }
    } finally {
        if ($archive -ne $null) { $archive.Dispose() }
    }
    return @($masters)
}

function ConvertTo-StencilMarkdown([object[]]$items, [string[]]$roots) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# Visio Stencil Index')
    $lines.Add('')
    $lines.Add('Generated by `scripts/visio_stencil_catalog.ps1` from local `.vssx/.vss` files.')
    $lines.Add('The index records file names, localized Master names, and `NameU` values for COM lookup.')
    $lines.Add('')
    $lines.Add('Scan roots:')
    foreach ($root in $roots) { $lines.Add('- `' + $root + '`') }
    $lines.Add('')
    $lines.Add('Found **' + @($items).Count + ' stencil files**. Legacy binary `.vss` files require Visio COM enumeration for names.')
    $lines.Add('')
    $lines.Add('## Quick Lookup')
    $lines.Add('')
    $lines.Add('| File | Master count | Sample names |')
    $lines.Add('| --- | ---: | --- |')
    foreach ($item in @($items | Sort-Object File)) {
        $names = @($item.Masters | ForEach-Object { if ($_.Name) { $_.Name } else { $_.NameU } })
        $sample = (@($names | Select-Object -First 8) -join '; ').Replace('|', '\|')
        $count = if ($null -eq $item.MasterCount) { 'COM required' } else { [string]$item.MasterCount }
        $lines.Add('| `' + $item.File + '` | ' + $count + ' | ' + $sample + ' |')
    }
    $lines.Add('')
    $lines.Add('## Full Catalog')
    $index = 0
    foreach ($item in @($items | Sort-Object File)) {
        $index++
        $lines.Add('')
        $lines.Add('### ' + $index + '. `' + $item.File + '`')
        $lines.Add('')
        $lines.Add('- File path: `' + $item.Path + '`')
        if ($null -eq $item.MasterCount) {
            $lines.Add('- Master count: enumerate with Visio COM (legacy binary `.vss`)')
            if ($item.Note) { $lines.Add('- Note: ' + $item.Note) }
            continue
        }
        $lines.Add('- Master count: ' + $item.MasterCount)
        $lines.Add('')
        $lines.Add('| # | Master name (localized) | NameU (stable name) |')
        $lines.Add('| ---: | --- | --- |')
        $number = 0
        foreach ($master in @($item.Masters)) {
            $number++
            $name = ([string]$master.Name).Replace('|', '\|')
            $nameU = ([string]$master.NameU).Replace('|', '\|')
            $lines.Add('| ' + $number + ' | ' + $name + ' | `' + $nameU + '` |')
        }
    }
    return ($lines -join [Environment]::NewLine)
}

$roots = @($RootPath)
if ($roots.Count -eq 0) { $roots = Get-DefaultStencilRoots }
$formatToUse = if ($PSBoundParameters.ContainsKey('Format')) {
    $Format
} elseif ($OutputPath) {
    'json'
} else {
    'table'
}

$files = New-Object System.Collections.Generic.List[string]
foreach ($root in $roots) {
    if (-not (Test-Path -LiteralPath $root -PathType Container)) {
        continue
    }
    foreach ($file in @(Get-ChildItem -LiteralPath $root -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Extension -in @('.vssx', '.vss') })) {
        if (-not $files.Contains($file.FullName)) { $files.Add($file.FullName) }
    }
}

$results = New-Object System.Collections.Generic.List[object]
foreach ($filePath in $files) {
    $file = Get-Item -LiteralPath $filePath
    $masters = @()
    $note = ''
    if ($file.Extension -ieq '.vssx') {
        try {
            $masters = @(Read-VssxMasters $file.FullName)
        } catch {
            $note = "Failed to read VSSX: $($_.Exception.Message)"
        }
    } else {
        $note = 'Legacy binary VSS; names were not read without starting Visio'
    }
    $sample = (@($masters | Select-Object -First 8 | ForEach-Object {
        if ($_.Name) { $_.Name } else { $_.NameU }
    }) -join ' | ')
    $results.Add([pscustomobject]@{
        File = $file.Name
        Path = $file.FullName
        MasterCount = if ($file.Extension -ieq '.vss') { $null } else { $masters.Count }
        SampleMasters = $sample
        Masters = @($masters)
        Note = $note
    })
}

if ($OutputPath) {
    $parent = Split-Path -Parent ([IO.Path]::GetFullPath($OutputPath))
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    if ($formatToUse -eq 'markdown') {
        $encoding = New-Object System.Text.UTF8Encoding($false)
        [IO.File]::WriteAllText($OutputPath, (ConvertTo-StencilMarkdown -items $results -roots $roots), $encoding)
    } else {
        $results | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $OutputPath -Encoding UTF8
    }
    Write-Output "Catalog written: $OutputPath"
} else {
    if ($results.Count -eq 0) {
        Write-Output 'No .vssx or .vss files found. Use -RootPath to specify Visio Content or My Shapes.'
    } elseif ($formatToUse -eq 'markdown') {
        Write-Output (ConvertTo-StencilMarkdown -items $results -roots $roots)
    } elseif ($formatToUse -eq 'json') {
        $results | ConvertTo-Json -Depth 5
    } else {
        $results | Sort-Object File | Format-Table File, MasterCount, SampleMasters, Note -AutoSize
    }
}
